---
spring:
    profiles: cloud
    data:
        mongodb:
            database: first-atomic-number
            username: example-user
            password: example-password
security:
  basic:
    enabled: false
