---

spring:
    profiles: cloud
    application:
        name: ${vcap.application.application_name:atomicnumproducer}
    data:
        mongodb:
            database: first-atomic-number
            username: example-user
            password: example-password
security:
  basic:
    enabled: false
